M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Monday 29 January 2024 07:20:14 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-29T19:20:14+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.22Y-1.41
X2.22Y-2.08
X2.98Y-1.41
X2.98Y-2.08
M30
